import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>New NextJS Tailwind App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-full w-full max-h-full max-w-full min-h-0 min-w-0 bg-slate-50 flex flex-col items-center justify-center'>
        <div className='text-slate-900 text-5xl font-medium text-center'>
          <div>NextJS</div>
          <div className='text-slate-400 font-light'>×</div>
          <div className='text-blue-700'>TypeScript</div>
          <div className='text-slate-400 font-light'>×</div>
          <div className='text-sky-400'>TailwindCSS</div>

          <div className='mt-10 text-sm'>By SYXWORKS /Daybreak.pub</div>
        </div>
      </main>
    </>
  )
}

export default Home
